### ISSUE TITLE
Add a new endpoint to filter build metadata

### ISSUE THREAD

**Issue by Arafo** [spotify/XCMetrics#108]
Hi!

I would love the ability to filter build metadata by key / value

For example:
Build 1 metadata
`
[
  "git_commit_sha": "build_1_sha.",
  "git_branch": "a_git_branch"
   "key_x": "another_value"
   ...
]
`

Build 2 metadata
`
[
  "git_commit_sha": "build_2_sha",
  "git_branch": "a_git_branch"
   "key_x": "another_value"
   ...
]
`

By being able to filter metadata by `git_branch` for example, I'd be able to get additional metadata fields from other builds which could help to analyze possible improvements or regressions.

Happy to propose an implementation if this is a welcomed addition.

Thanks!

**Comment by BalestraPatrick** [comment]
Hey @Arafo! I think this would be a great addition and we would welcome such a change. 👍
