### ISSUE TITLE
How to retain only the most basic and core data? Such as build time/cpu/memory, full/incremental compilation and other data.

### ISSUE THREAD

**Issue by Jinxiansen** [spotify/XCMetrics#114]
Hi, guys
We have an iOS project with millions of lines and more than 6000+ warning messages. Each compilation will generate a lot of logs. **I tried compiling locally several times and generated more than 300M of data**. We have dozens of iOS members and if they will all Uploading this data every time to the server will generate a lot of traffic and storage pressure.

Therefore, I want to know if there is any way for us to record only the most basic and core data, such as build time/cpu/memory, full/incremental compilation and other data.
Discarding overly detailed data such as each step/warning information will greatly reduce and save the pressure on the deployed server.

In addition, the `.xcactivitylog` file exceeds 20MB and uploading will be time-consuming. Do we have any compression solution?

<img width="639" alt="image" src="https://github.com/spotify/XCMetrics/assets/16829428/5663abfa-4cd1-4345-9338-5443aeb8839d">

That's just about one-tenth of the traffic, which is already so much.
<img width="517" alt="image" src="https://github.com/spotify/XCMetrics/assets/16829428/1478237b-ca9f-4294-b22f-c212f5301b2f">

**Comment by jkmathew** [comment]
Hey @Jinxiansen,
Did you manage to solve this?
I am also facing the same issue. Since the storage is costly and autoscaling is not enabled, we regularly get the SQL instance stopped because of storage quota is exceeded. 

@BalestraPatrick sorry to tag you, your input is much appreciated.

**Comment by Jinxiansen** [comment]
> Hey @Jinxiansen,
> Did you manage to solve this?
> I am also facing the same issue. Since the storage is costly and autoscaling is not enabled, we regularly get the SQL instance stopped because of storage quota is exceeded. 
> 
> @BalestraPatrick sorry to tag you, your input is much appreciated.

We modified the source code to remove large data, refer to the following changes:

```
//        let warnings = parseWarnings(buildSteps: buildSteps, targets: targetBuildSteps, steps: steps, buildIdentifier: buildIdentifier)
//        let errors = parseErrors(buildSteps: buildSteps, targets: targetBuildSteps, steps: steps, buildIdentifier: buildIdentifier)
//        let notes = parseNotes(buildSteps: buildSteps, targets: targetBuildSteps, steps: steps, buildIdentifier: buildIdentifier)

        let functionBuildTimes = steps.compactMap { step in
            step.swiftFunctionTimes?.map {
@@ -160,12 +160,13 @@ struct LogParser {
            }
        }.joined()

        #warning("Skip these large data to save disk.")
        return BuildMetrics(build: build,
                            targets: [],
                            steps: [],
                            warnings: [],
                            errors: [],
                            notes: [],
                            swiftFunctions: Array(functionBuildTimes),
```

**Comment by Jinxiansen** [comment]
@jkmathew FYI

**Comment by jkmathew** [comment]
Thanks for the hint @Jinxiansen ,
do you mind opening a PR with a more dynamic selection like an env variable or so?
