### ISSUE TITLE
Detect CI environment variable

### ISSUE THREAD

**Issue by FranzBusch** [spotify/XCMetrics#19]
Most CI system are automatically populating the build environment with a variable `CI` to indicate that the build is running on a CI system. It would be great if we can automatically detect that variable from the environment instead of passing it to the `XCMetrics` invocation by hand.

If this is something you think is useful, I would be very happy to open a PR for it.

**Comment by FranzBusch** [comment]
I am closing this since it seems to be working when using `--isCI ${CI:-false}` inside the post build script

**Comment by ecamacho** [comment]
Clever!
