### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by bolismauro** [spotify/XCMetrics#23]
Hi! 
I'm trying XCMetrics to see how we can leverage it within our organization.
One thing that it is not clear to me is whether the web interface that is shown in the presentation video is included in the project.

I've read the documentation and deployed locally the server, but it looks like there is only the part of the backend that gather metrics. Is that correct?

Thanks a lot

**Comment by bolismauro** [comment]
I just re-listened the video and it says the web interface is experimental. I guess this is the reason it is not included :) 

I'll keep this monitored, thanks a lot!

**Comment by AgapovOne** [comment]
It would be great to have a list of html pages, that [XCLogParser](https://github.com/spotify/XCLogParser) parser with html report creates with links to it.

I guess that's the next destination of current public release, without any additional analytics over a bunch of builds. Probably we need a fork now :)
