### ISSUE TITLE
[feature request] Can you please open source your SPTXCMetrics?

### ISSUE THREAD

**Issue by tinder-kaijing** [spotify/XCMetrics#27]
Is it possible to open source your common/popular metrics, for instance, some metrics from your internal SPTXCMetrics?

**Comment by BalestraPatrick** [comment]
Some of the plugins we use are available here: https://github.com/spotify/XCMetrics/tree/main/Sources/XCMetricsPlugins

Some others are very specific to our infra and would probably not benefit the wider community.

**Comment by BalestraPatrick** [comment]
I'm going to close this issue, but feel free to comment if you need more pointers.
