### ISSUE TITLE
[feature request] Can support a new flag, "--isCD"

### ISSUE THREAD

**Issue by tinder-kaijing** [spotify/XCMetrics#28]
In our CI/CD system, they are separated. so, could we please support a new flag,  "--isCD"?

**Comment by BalestraPatrick** [comment]
As described in our [docs](https://github.com/spotify/XCMetrics/blob/main/docs/Getting%20Started.md#plugin-architecture-overview), the core component of XCMetrics is not going to accept new flags. You can extend the tool by writing your own plugins that could for example read and environment variable that will help you track CI and CD builds separately.
