### ISSUE TITLE
[doc] Is there any documentation about the database schema, table?

### ISSUE THREAD

**Issue by tinder-kaijing** [spotify/XCMetrics#29]
I try to use Grafana to create metrics that will view data sources in Postgres directly. so I need to know the data, the schemas, and their tables, data relationship in each table. Are there any documents about them?
I can guess most of the tables, columns, but it will be easy if we have documentation about them.

**Comment by BalestraPatrick** [comment]
I don't think we have clear docs on this, but the following two resources should be helpful:
- https://github.com/spotify/XCMetrics/blob/main/proto/xcmetrics/v1/xcmetrics.proto
- https://github.com/spotify/XCMetrics/tree/main/Sources/XCMetricsBackendLib/Common/Models

**Comment by BalestraPatrick** [comment]
I'm going to close this issue, but feel free to comment if you more pointers.

**Comment by kzin** [comment]
Hey @tinder-kaijing did you create metrics on grafana?

**Comment by 1ucas** [comment]
I'm in the same situation here.

To keep a weekly report, is it safe to just 
```
DELETE FROM build_XYZ
WHERE day < (now() - '7'::interval)
```
on all tables starting with the "build" prefix?

**Comment by tinder-kaijing** [comment]
> Hey @tinder-kaijing did you create metrics on grafana?

sorry, I missed the message. Yes, I created metrics on grafana :-).
