### ISSUE TITLE
What tools were used to create the gif?

### ISSUE THREAD

**Issue by ChaiBapchya** [spotify/XCMetrics#33]
I found the xcmetrics working gif pretty useful to understand the tool. I was curious to learn how that gif was created? What tools were used to design/create it? 

https://github.com/spotify/XCMetrics/blob/gh-pages/images/xcmetrics-open-source-xcode-tool.gif

**Comment by ChaiBapchya** [comment]
For static images, I use draw.io 
However for such gifs, what tools are used? Is it a matter of overlaying multiple static images to form a gif? Are there some tools that make this easier?

**Comment by BalestraPatrick** [comment]
A interactive designer designed it for us, and I think some more complex program such as Adobe Animate was used.
