### ISSUE TITLE
Question: Just wondering if we can use configuration file when backend deployment

### ISSUE THREAD

**Issue by AyaAkl25** [spotify/XCMetrics#34]
So because we will be adding the database username and password when deploying the backend, is there another way to build this with a configuration file so that we could encrypt the password/username.

Thank you :)

**Comment by ecamacho** [comment]
How are you deploying? You can rely on your cloud provider to do this. For instance, if you're using Kubernetes you can use [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/).

**Comment by BalestraPatrick** [comment]
Going to close this issue since it doesn't seem related to XCMetrics itself, but rather on how to deploy securely a backend which widely depends on which cloud provider you're deploying to.
