### ISSUE TITLE
Question: Duration is which time unit?

### ISSUE THREAD

**Issue by AyaAkl25** [spotify/XCMetrics#39]
Hey, 
I have a question regarding the duration double value for builds, which time unit is it.. microseconds or milliseconds?

Thank you

**Comment by akkrat** [comment]
Seems like it's megaseconds :) i.e. actual duration = duration * 1000000
You can simply check it calculating the difference between end_timestamp and start_timestamp columns

**Comment by AyaAkl25** [comment]
> Seems like it's megaseconds :) i.e. actual duration = duration * 1000000
> You can simply check it calculating the difference between end_timestamp and start_timestamp columns

Thank you :)
