### ISSUE TITLE
[Questions] two questions regarding XCMetrics database columns

### ISSUE THREAD

**Issue by AyaAkl25** [spotify/XCMetrics#40]
Hey guys, 

after playing around XCMetrics and checking the data saved in database I have two questions just to clarify my information:
1- What is the difference of targets types saved in database (builds or build_targets) for noop, clean, or incremental?
2- What is the difference between duration and compilation duration?

Thank you and have a great day!

**Comment by polac24** [comment]
Hi! 
* You can find build and target types description here: https://github.com/spotify/XCMetrics/blob/0f449cc9dc328de3fcd85e08edec18f43da3a041/Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift#L226-L244
* Regarding compilation duration: it counts only time for compilation steps (like swiftc, clang) and all other, like custom scripts, are not considered. [Docs](https://github.com/spotify/XCLogParser/blob/master/docs/JSON%20Format.md)

**Comment by AyaAkl25** [comment]
> Hi!
> 
> * You can find build and target types description here: https://github.com/spotify/XCMetrics/blob/0f449cc9dc328de3fcd85e08edec18f43da3a041/Sources/XCMetricsBackendLib/UploadMetrics/LogProcessing/LogParser.swift#L226-L244
> * Regarding compilation duration: it counts only time for compilation steps (like swiftc, clang) and all other, like custom scripts, are not considered. [Docs](https://github.com/spotify/XCLogParser/blob/master/docs/JSON%20Format.md)

that's perfect, thanks a lot!
