### ISSUE TITLE
Docker Image Version Tags

### ISSUE THREAD

**Issue by dlbuckley** [spotify/XCMetrics#43]
We are deploying XCMetrics to AWS using Elastic Beanstalk to pull the latest docker image from docker hub. At the moment we can only deploy the latest version of XCMetrics as that is the only tag available, but we would like control over which version we deploy.

Could the versions start to be tagged in addition to `latest` in docker hub so we can control which version we deploy?

Docker Hub Tags: https://hub.docker.com/r/spotify/xcmetrics/tags?page=1&ordering=last_updated

**Comment by ecamacho** [comment]
We have enabled this. One tag is automatically created with each release: https://hub.docker.com/r/spotify/xcmetrics/tags?page=1&ordering=last_updated

**Comment by dlbuckley** [comment]
Awesome, thank you ❤️
