### ISSUE TITLE
Log not send when executed from terminal via xcodebuild.

### ISSUE THREAD

**Issue by kronenthaler** [spotify/XCMetrics#45]
I have been gathering logs compiling directly from Xcode without problem. I tried to run the xcodebuild command to automate some experiments, and i noticed the log are not being sent.

I have redirected the output of the post action to a file, but nothing is printed there. I run the same project unmodified from Xcode and the logs are sent with no problem.

Any tips or pointers will be appreciated!

**Comment by ecamacho** [comment]
How are you running xcodebuild? Since Xcode 11, xcodebuild only generates the build logs when the option `-resultBundlePath`. Be sure to set that option to a valid path.

**Comment by kronenthaler** [comment]
Thanks i will give it a try. Feel free to close the ticket.
