### ISSUE TITLE
seems the recent commit "Facilitate additional auth headers to be included within the metrics" doesn't upload build log files

### ISSUE THREAD

**Issue by tinder-kaijing** [spotify/XCMetrics#47]
it seems that the recent merge "Facilitate additional auth headers to be included within the metrics" break the build log files uploading for some reason. I did not dig into detail to find why? someone else has the same issue?

**Comment by ecamacho** [comment]
Did you try using the latest docker image? https://hub.docker.com/r/spotify/xcmetrics/tags?page=1&ordering=last_updated

**Comment by tinder-kaijing** [comment]
@ecamacho That's correct. forget to update the latest XCMetricsBackend service :-). Close it without an issue.
