### ISSUE TITLE
Looking forward to the Web Interface

### ISSUE THREAD

**Issue by Binlogo** [spotify/XCMetrics#52]
XCLogParser & XCMetrics is cool idea, the demo shows the graph is pretty.
Is there any plan to integrate the web interface to the XCMetric service? 🚀🚀🚀

**Comment by ngranander** [comment]
Hi @Binlogo, awesome that you're interested in XCMetrics!
Currently, a user interface is being developed as a plugin for [Backstage](https://backstage.io/). It's still in an early stage but free to [check it out](https://github.com/backstage/backstage/issues/6258) 😄

**Comment by Binlogo** [comment]
> Hi @Binlogo, awesome that you're interested in XCMetrics!
> Currently, a user interface is being developed as a plugin for [Backstage](https://backstage.io/). It's still in an early stage but free to [check it out](https://github.com/backstage/backstage/issues/6258) 😄

Nice! I'd like to have a try.
