### ISSUE TITLE
Where the enqueued daily statistics job are started?

### ISSUE THREAD

**Issue by ronanrodrigo** [spotify/XCMetrics#67]
I am trying get values from `DailyStatisticsJob` at `/v1/statistics/build/count?days=14`  but the `statistics_day_build_time` table is empty. And while debugging the `XCMetricsBackendLib/Config/configure.swift` there isn't a call to `startScheduledJobs()` or similar across the project.

I am missing where it is being called? Or there is other way to start the scheduled jobs?

**Comment by ronanrodrigo** [comment]
Adding this to my project the table started to being populated

```swift
public func configure(_ app: Application) throws {

    // ...

    if config.scheduleStatisticsJobs {
        // ...
        try app.queues.startScheduledJobs()
    }

    // ...
}
```

**Comment by ronanrodrigo** [comment]
I found some other stuffs... On `routes.swift` the `try app.queues.startInProcessJobs(on: .default)` and on `xcmetrics-jobs-deployment.yaml` this:

```
command: ["./XCMetricsBackend",
    "queues",
    "--env",
    "production"]
```

But even running the command above, nothing happens. There is any documentation about the workers/schedulers?

**Comment by ecamacho** [comment]
Hi. You need to start the process with

```yaml
        command: ["./XCMetricsBackend",
                  "queues",
                  "--scheduled",
                  "--env",
                  "production"]
```

It will run every day and create the `statistics_day_counts` table.

I will add documentation about this.

**Comment by ronanrodrigo** [comment]
@ecamacho thanks!
