### ISSUE TITLE
Question: Will and when uploaded xcactivitylog be deleted?

### ISSUE THREAD

**Issue by dwirandyh** [spotify/XCMetrics#80]
Hi there
As far as i know xcmetrics will copied xcactivitylog from derived data to ~/Library/Caches/XCMetrics, So I think, the longer this folder will contain a lot of .xcactivitylogs and will require a lot of storage space on the hard disk, 
Can xcmetrics delete xcactivitylog automatically? perhaps Instead of renaming the file with UPLOADED.xcactivitylog can we just delete it?

**Comment by polac24** [comment]
There is a code to evict logs older than 7d:
https://github.com/spotify/XCMetrics/blob/0f449cc9dc328de3fcd85e08edec18f43da3a041/Sources/XCMetricsClient/Log%20Management/LogManager.swift#L192

**Comment by dwirandyh** [comment]
thanks @polac24
